### ISSUE TITLE
Latest release won't build in Carthage with Xcode 10.2

### ISSUE THREAD

**Issue by rzulkoski** [toineheuvelmans/Metron#17]
The latest release won't build in Carthage with Xcode 10.2 due to Swift 3.0 being deprecated.

The master branch is compatible, but a new release hasn't been created yet. @toineheuvelmans would it be possible to create a new release including the new changes on `master`?

**Comment by iby** [comment]
@rzulkoski 1.0.3 should fix this. Let know if there're any troubles?

**Comment by rzulkoski** [comment]
Works great, thanks @ianbytchek!
