### ISSUE TITLE
Podspec is on 1.0.3 while release is on 1.0.4

### ISSUE THREAD

**Issue by RubenAstudillo** [toineheuvelmans/Metron#19]
Hi, thanks for all your work!.

I noticed the tagged release is on 1.0.4 but the spec file is on 1.0.3. I import this project via github and grabs that version. Another issue is that on cocoapods the version available is 1.0.2 which doesn't build on swift 5, maybe also update that?

**Comment by iby** [comment]
@RubenAstudillo Thanks for bringing this up! @toineheuvelmans I bumped the version, could you `pod repo push`?

**Comment by toineheuvelmans** [comment]
(`pod trunk push` 😉)
```
🎉  Congrats

 🚀  Metron (1.0.4) successfully published
 📅  July 5th, 09:12
 🌎  https://cocoapods.org/pods/Metron
 👍  Tell your friends!
```

**Comment by iby** [comment]
🤷‍♂️
