### ISSUE TITLE
Build error using XCode9 / Swift 4 in Polygon, sorted

### ISSUE THREAD

**Issue by erf** [toineheuvelmans/Metron#5]
Build error using XCode9 / Swift 4. Polygon, sorted requires two arguments. 

Link:
https://github.com/toineheuvelmans/Metron/blob/712905ebd8efe7340f86bb74694de637cccd85fa/Metron/Classes/Polygon.swift#L233

**Comment by toineheuvelmans** [comment]
@erf I fixed the issue you mentioned in a `swift4` branch: https://github.com/toineheuvelmans/Metron/tree/swift4
