### ISSUE TITLE
Typo in Triangle function circumcenter() 

### ISSUE THREAD

**Issue by aroyarexs** [toineheuvelmans/Metron#6]
Currently the name is ci**cr**umcenter but the correct name is ci**rc**umcenter.

**Comment by toineheuvelmans** [comment]
Hey @aroyarexs, thanks for your sharp observation, I'll make sure to fix it in the next release.

**Comment by toineheuvelmans** [comment]
@aroyarexs I have released version 1.0.1, which includes the fixed typo you mentioned. Thanks again for your input!
