### ISSUE TITLE
Trouble getting Example playground to run.

### ISSUE THREAD

**Issue by davidbjames** [toineheuvelmans/Metron#7]
Hi! Great library!

I'm getting this error when attempting to run the example playground:

    error: /var/folders/y0/p7w_bnh91nv7vsl4kcymcxbh0000gq/T/playground6-adf4ec..swift:3:8: error: no such module 'Metron_Sources'
    import Metron_Sources

Any ideas?

BTW, suggest adding a note about running `pod install`. From the Playground:
> NOTE: **Run pod install in the Example folder and then open the Xcode workspace.** You will need to build the project first before Metron is available in these playgrounds. Ensure that you have a Simulator-type device selected when building.

**Comment by davidbjames** [comment]
Appears the fix is to add `public` visibility to the extensions in Sources/Playground.swift. :)

**Comment by toineheuvelmans** [comment]
Hi @davidbjames , thanks for pointing this out, I have applied the required changes and addition to the note that you mentioned. Please see release 1.0.2.
